env_args:
  env: simple_pyramid
  param:
    depth: 6
    hyperplane_dim: 2
    general_seed: -1
    start_random: true
    features:
      seed: -1
      dim: 2
      obs_var: 0.01
    rewards:
      depth:
      - 6
      coordinates:
      - - 1
        - 5
      type:
      - fix
      mu:
      - 1.0
      var:
      - 0.0
train_args:
  default_learning_rate: 3.0e-08
  gamma: 1.0
  forward_steps: 2
  entropy_regularization: 0.001
  update_episodes: 300
  batch_size: 256
  minimum_episodes: 10000
  maximum_episodes: 20000
  epochs: 30
  eval_rate: 0.1
  policy_target: TD-Q
  value_target: TD-Q
  eval:
    opponent:
    - random
  seed: 0
  agent:
    type: SRS_v2_v3
    use_RND: false
  metadata:
    name:
    - knn
    - global_aleph
    - regional_weight
    - global_return_size
    - global_eta
    eval_base: QL
    knn:
      size: 10000
      k: 64
    regional_weight: 1.0
    global_aleph: 1.0
    global_return_method: Mean
    global_return_size: 100
    global_eta: 0.5
worker_args:
  server_address: 0.0.0.0
  num_parallel: 128
